# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

version: "{build}"

environment:
  matrix:
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"

build: off

branches:
  only:
    - master
